# Mark Pipko and Joshua Mimer
# I pledge my honor that I have abided by the Stevens Honor System.

CC     = gcc
CFLAGS = -Wall -Werror -pedantic-errors
all:
		$(CC) $(CFLAGS) -o chatclient chatclient.c 
clean:
		rm chatclient 
